name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kód
        uses: actions/checkout@v4
        
      - name: Nastavení Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Instalace balíčků
        run: npm install
        
      - name: Sestavení webu (Build)
        run: npm run build
        
      - name: Nahrání hotového webu
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Nasazení na Pages
        id: deployment
        uses: actions/deploy-pages@v4